spring:
  datasource:
    url: jdbc:h2:file:./moviescape;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    tomcat:
      testWhileIdle: true
      validationQuery: "SELECT 1"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080